# Generated by Django 4.1.4 on 2022-12-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movieorder_movie_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="orders",
            new_name="users",
        ),
        migrations.RenameField(
            model_name="movieorder",
            old_name="order",
            new_name="user",
        ),
    ]
